name: generis_example
description: example
version: 1.0.1
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

publish_to: none
dependencies:
  generis:
    path: ../generis
dev_dependencies:
  build_runner: ^2.0.4
  generis_generator:
    path: ../generator
