name: generis_generator
description: Generis
version: 0.0.1
homepage: https://github.com/smotastic/smartstruct
environment:
  sdk: ">=2.12.0 <3.0.0"
publish_to: none
dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.17.7
  source_gen_test: ^1.0.0
dependencies:
  analyzer: ^1.7.1
  build: ^2.0.2
  source_gen: ^1.0.1
  code_builder: ^4.0.0
  generis:
    path: '../generis'
  path: ^1.8.0
